### ISSUE TITLE
Bump Kafka to version 3.3.1

### ISSUE THREAD

**Issue by patpatpat123** [moeenz/docker-kafka-kraft#1]
Happy New Year!

Best wishes for 2023.

Big thanks for this cool project.

May I ask if it is possible to bump the Kafka version up to the latest (as of this writing) which is 3.3.1 please?

Thank you!

**Comment by moeenz** [comment]
Hello and Happy new year!

Although 2024 seems a bit far but thanks for the wishes!

The version for Kafka is now set to 3.3.1.

**Comment by patpatpat123** [comment]
Typo corrected.

Many thanks for the bump!

Best wishes for 2023!

**Comment by melloware** [comment]
Much appreciated for this I have been looking for a simple docker Kafka without Zookeeper and allows me to create topics in the config. Yours meets all those requirements so thank you!
