### ISSUE TITLE
Eclipse Temurin image

### ISSUE THREAD

**Issue by melloware** [moeenz/docker-kafka-kraft#2]
Have you tried using the Alpine OpenJDk image which is the smallest around instead of the Slim Buster?

Also I saw a small spelling mistake in your shell script spelling "Environment" incorrectly. 

Thanks for this!

**Comment by moeenz** [comment]
Thanks for the comment 🙏
Can you send the link to the exact image you're referring to?

**Comment by melloware** [comment]
So `temurin` is the official JDK from Adoptium and the image most GitHub Actions use now.

https://hub.docker.com/_/eclipse-temurin

So it would be...

`eclipse-temurin:<version>-alpine`

`docker pull eclipse-temurin:8u352-b08-jre`

**Comment by melloware** [comment]
And to update the reason most people moved to temurin is OpenJDK has deprecated theirs recommending people use Temurin.  

> This image is officially deprecated and all users are recommended to find and use suitable replacements ASAP. 

https://hub.docker.com/_/openjdk

**Comment by melloware** [comment]
Also sorry to bother you i would try going with JDK 11 or 17.   More and more projects are getting away from 8 even though I know it still has Long Term Support.

**Comment by melloware** [comment]
And here is a great explanation of Apline: https://jpetazzo.github.io/2020/03/01/quest-minimal-docker-images-part-2/

**Comment by moeenz** [comment]
hey! extremely sorry for the super late action but the `openjdk` image is now replaced with `eclipse-temurin`.

**Comment by melloware** [comment]
Nice work @moeenz !!!
